export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const GET_USER_POSTS_REQUEST = "GET_USER_POSTS_REQUEST";
export const GET_USER_POSTS_SUCCESS = "GET_USER_POSTS_SUCCESS";
export const GET_USER_POSTS_FAIL = "GET_USER_POSTS_FAIL";

export const SIGIN_IN_USER_REQUEST = "SIGIN_IN_USER_REQUEST";
export const SIGIN_IN_USER_SUCCESS = "SIGIN_IN_USER_SUCCESS";
export const SIGIN_IN_USER_FAIL = "SIGIN_IN_USER_FAIL";
